// <auto-generated />
using HotChocolateDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotChocolateDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210108212454_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HotChocolateDemo.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Borrowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adam",
                            SharedId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mike",
                            SharedId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luke",
                            SharedId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sean",
                            SharedId = 2
                        });
                });

            modelBuilder.Entity("HotChocolateDemo.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            SharedId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150m,
                            SharedId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200m,
                            SharedId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 220m,
                            SharedId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 270m,
                            SharedId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
